name: plant-disease-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - pillow
  - opencv
  - pathlib
  - jupyter
  - notebook
  - pip:
    - tensorflow==2.15.0
    - keras==2.15.0
    - opencv-python==4.8.1.78
    - albumentations==1.3.1
    - plotly==5.17.0
    - streamlit==1.28.1
    - pytest==7.4.3
    - black==23.11.0
    - ruff==0.1.6
    - pre-commit==3.6.0